import os

BASE_DIR = os.path.abspath(os.path.dirname(__file__))

EIA_API_KEY = 'D82A092DA301308805ECAB18A123BB4A'

STATES = {
    'AK': ['Alaska', 'alaska'],
    'AL': ['Alabama', 'alabama'],
    'AR': ['Arkansas', 'arkansas'],
    'AS': ['American Samoa', 'american_samoa'],
    'AZ': ['Arizona', 'arizona'],
    'CA': ['California', 'california'],
    'CO': ['Colorado', 'colorado'],
    'CT': ['Connecticut', 'connecticut'],
    'DC': ['District of Columbia', 'district_of_columbia'],
    'DE': ['Delaware', 'delaware'],
    'FL': ['Florida', 'florida'],
    'GA': ['Georgia', 'georgia'],
    'GU': ['Guam', 'guam'],
    'HI': ['Hawaii', 'hawaii'],
    'IA': ['Iowa', 'iowa'],
    'ID': ['Idaho', 'idaho'],
    'IL': ['Illinois', 'illinois'],
    'IN': ['Indiana', 'indiana'],
    'KS': ['Kansas', 'kansas'],
    'KY': ['Kentucky', 'kentucky'],
    'LA': ['Louisiana', 'louisiana'],
    'MA': ['Massachusetts', 'massachusetts'],
    'MD': ['Maryland', 'maryland'],
    'ME': ['Maine', 'maine'],
    'MI': ['Michigan', 'michigan'],
    'MN': ['Minnesota', 'minnesota'],
    'MO': ['Missouri', 'missouri'],
    'MP': ['Northern Mariana Islands', 'northern_mariana_islands'],
    'MS': ['Mississippi', 'mississippi'],
    'MT': ['Montana', 'montana'],
    'NA': ['National', 'national'],
    'NC': ['North Carolina', 'north_carolina'],
    'ND': ['North Dakota', 'north_dakota'],
    'NE': ['Nebraska', 'nebraska'],
    'NH': ['New Hampshire', 'new_hampshire'],
    'NJ': ['New Jersey', 'new_jersey'],
    'NM': ['New Mexico', 'new_mexico'],
    'NV': ['Nevada', 'nevada'],
    'NY': ['New York', 'new_york'],
    'OH': ['Ohio', 'ohio'],
    'OK': ['Oklahoma', 'oklahoma'],
    'OR': ['Oregon', 'oregon'],
    'PA': ['Pennsylvania', 'pennsylvania'],
    'PR': ['Puerto Rico', 'puerto_rico'],
    'RI': ['Rhode Island', 'rhode_island'],
    'SC': ['South Carolina', 'south_carolina'],
    'SD': ['South Dakota', 'south_dakota'],
    'TN': ['Tennessee', 'tennessee'],
    'TX': ['Texas', 'texas'],
    'UT': ['Utah', 'utah'],
    'VA': ['Virginia', 'virginia'],
    'VI': ['Virgin Islands', 'virgin_islands'],
    'VT': ['Vermont', 'vermont'],
    'WA': ['Washington', 'washington'],
    'WI': ['Wisconsin', 'wisconsin'],
    'WV': ['West Virginia', 'west_virginia'],
    'WY': ['Wyoming', 'wyoming'],
}


RPS_STATES = {
    'AZ': {'names': ['arizona', 'Arizona', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'CA': {'names': ['california', 'California', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'CO': {'names': ['colorado', 'Colorado', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'HI': {'names': ['hawaii', 'Hawai&lsquo;i', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'IL': {'names': ['illinois', 'Illinois', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'IA': {'names': ['iowa', 'Iowa', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'KS': {'names': ['kansas', 'Kansas', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'MD': {'names': ['maryland', 'Maryland', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'MI': {'names': ['michigan', 'Michigan', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'ME': {'names': ['maine', 'Maine', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'MT': {'names': ['montana', 'Montana', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'NV': {'names': ['nevada', 'Nevada', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'NJ': {'names': ['new_jersey', 'New Jersey', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'NC': {'names': ['north_carolina', 'North Carolina', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'OH': {'names': ['ohio', 'Ohio', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'OR': {'names': ['oregon', 'Oregon', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'RI': {'names': ['rhode_island', 'Rhode Island', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'WA': {'names': ['washington', 'Washington', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
    'WI': {'names': ['wisconsin', 'Wisconsin', ],
           'green_energy': ['BMTCB', 'GETCB', 'HYTCB', 'SOTCB', 'WYTCB']},
}

CARBON_INTENSITY = {
    'Biomass': 1,
    'Coal': 890,
    'Distillate Fuel Oil': 670,
    'Geothermal': 1,
    'Hydroelectricity': 1,
    'Kerosene': 650,
    'LPG': 500,
    'Natural Gas as Lease and Plant Fuel': 400,
    'Nuclear Electricity': 1,
    'Residual Fuel Oil': 670,
    'Solar': 1,
    'Supplemental Gaseous Fuels': 9999,
    'Wind': 1,
    'Wood and Waste': 9999,
}