import os

BASE_DIR = os.path.abspath(os.path.dirname(__file__))

EIA_API_KEY = 'D82A092DA301308805ECAB18A123BB4A'

STATES = {
    'AK': ['Alaska', 'alaska'],
    'AL': ['Alabama', 'alabama'],
    'AR': ['Arkansas', 'arkansas'],
    'AS': ['American Samoa', 'american_samoa'],
    'AZ': ['Arizona', 'arizona'],
    'CA': ['California', 'california'],
    'CO': ['Colorado', 'colorado'],
    'CT': ['Connecticut', 'connecticut'],
    'DC': ['District of Columbia', 'district_of_columbia'],
    'DE': ['Delaware', 'delaware'],
    'FL': ['Florida', 'florida'],
    'GA': ['Georgia', 'georgia'],
    'GU': ['Guam', 'guam'],
    'HI': ['Hawaii', 'hawaii'],
    'IA': ['Iowa', 'iowa'],
    'ID': ['Idaho', 'idaho'],
    'IL': ['Illinois', 'illinois'],
    'IN': ['Indiana', 'indiana'],
    'KS': ['Kansas', 'kansas'],
    'KY': ['Kentucky', 'kentucky'],
    'LA': ['Louisiana', 'louisiana'],
    'MA': ['Massachusetts', 'massachusetts'],
    'MD': ['Maryland', 'maryland'],
    'ME': ['Maine', 'maine'],
    'MI': ['Michigan', 'michigan'],
    'MN': ['Minnesota', 'minnesota'],
    'MO': ['Missouri', 'missouri'],
    'MP': ['Northern Mariana Islands', 'northern_mariana_islands'],
    'MS': ['Mississippi', 'mississippi'],
    'MT': ['Montana', 'montana'],
    'NA': ['National', 'national'],
    'NC': ['North Carolina', 'north_carolina'],
    'ND': ['North Dakota', 'north_dakota'],
    'NE': ['Nebraska', 'nebraska'],
    'NH': ['New Hampshire', 'new_hampshire'],
    'NJ': ['New Jersey', 'new_jersey'],
    'NM': ['New Mexico', 'new_mexico'],
    'NV': ['Nevada', 'nevada'],
    'NY': ['New York', 'new_york'],
    'OH': ['Ohio', 'ohio'],
    'OK': ['Oklahoma', 'oklahoma'],
    'OR': ['Oregon', 'oregon'],
    'PA': ['Pennsylvania', 'pennsylvania'],
    'PR': ['Puerto Rico', 'puerto_rico'],
    'RI': ['Rhode Island', 'rhode_island'],
    'SC': ['South Carolina', 'south_carolina'],
    'SD': ['South Dakota', 'south_dakota'],
    'TN': ['Tennessee', 'tennessee'],
    'TX': ['Texas', 'texas'],
    'UT': ['Utah', 'utah'],
    'VA': ['Virginia', 'virginia'],
    'VI': ['Virgin Islands', 'virgin_islands'],
    'VT': ['Vermont', 'vermont'],
    'WA': ['Washington', 'washington'],
    'WI': ['Wisconsin', 'wisconsin'],
    'WV': ['West Virginia', 'west_virginia'],
    'WY': ['Wyoming', 'wyoming'],
}

RPS_STATES = [
    ('arizona', 'Arizona', 'AZ'),
    ('california', 'California', 'CA'),
    ('colorado', 'Colorado', 'CO'),
    ('hawaii', 'Hawai&lsquo;i', 'HI'),
    ('illinois', 'Illinois', 'IL'),
    ('iowa', 'Iowa', 'IA'),
    ('kansas', 'Kansas', 'KS'),
    ('maryland', 'Maryland', 'MD'),
    ('michigan', 'Michigan', 'MI'),
    ('maine', 'Maine', 'ME'),
    ('montana', 'Montana', 'MT'),
    ('nevada', 'Nevada', 'NV'),
    ('new_jersey', 'New Jersey', 'NJ'),
    ('north_carolina', 'North Carolina', 'NC'),
    ('ohio', 'Ohio', 'OH'),
    ('oregon', 'Oregon', 'OR'),
    ('rhode_island', 'Rhode Island', 'RI'),
    ('washington', 'Washington', 'WA'),
    ('wisconsin', 'Wisconsin', 'WI'),
]

CARBON_INTENSITY = {
    'Biomass': 1,
    'Coal': 890,
    'Distillate Fuel Oil': 670,
    'Geothermal': 1,
    'Hydroelectricity': 1,
    'Kerosene': 650,
    'LPG': 500,
    'Natural Gas as Lease and Plant Fuel': 400,
    'Nuclear Electricity': 1,
    'Residual Fuel Oil': 670,
    'Solar': 1,
    'Supplemental Gaseous Fuels': 9999,
    'Wind': 1,
    'Wood and Waste': 9999,
}