EIA_FUEL_SECTORS = [
    {'sector': 'Biomass', 'code': 'BMTCB', 'intensity': 1},
    {'sector': 'Coal', 'code': 'CLTCB', 'intensity': 890},
    {'sector': 'Distillate Fuel Oil', 'code': 'DFTCB',
     'intensity': 670},
    {'sector': 'Geothermal', 'code': 'GETCB', 'intensity': 1},
    {'sector': 'Hydroelectricity', 'code': 'HYTCB', 'intensity': 1},
    {'sector': 'Kerosene', 'code': 'KSTCB', 'intensity': 650},
    {'sector': 'LPG', 'code': 'LGTCB', 'intensity': 500},
    {'sector': 'Natural Gas', 'code': 'NNTCB',
     'intensity': 400},
    {'sector': 'Nuclear Electricity', 'code': 'NUETB', 'intensity': 1},
    {'sector': 'Residual Fuel Oil', 'code': 'RFTCB', 'intensity': 670},
    {'sector': 'Solar', 'code': 'SOTCB', 'intensity': 1},
    {'sector': 'Supp. Gaseous Fuels', 'code': 'SFTCB',
     'intensity': 9999},
    {'sector': 'Wind', 'code': 'WYTCB', 'intensity': 1},
    {'sector': 'Wood and Waste', 'code': 'WWTCB', 'intensity': 9999},
]

